# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170807_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='published_date',
            new_name='pub_date',
        ),
    ]
